#!/bin/bash

set -eu

source "utils/common"

function teardown {
    stackip=$(pidof lvl-ip) || true
    [[ $stackip ]] && kill "$stackip"
}

trap teardown EXIT ERR
# trap teardown EXIT

start_stack
echo "Started lvl-ip, wait for stack to establish itself" && sleep 5

lvl_ip_check
pids=""

tc qdisc add dev tap0 root handle 1: htb

# udp 测试 START
./suites/udp/suite-udp &
pids="$pids $!"
# udp 测试 END
# !!! 这里不能直接exit, 否则会导致lvl-ip进程退出
# !!! 这里不能直接exit, 否则会导致lvl-ip进程退出
# !!! 这里不能直接exit, 否则会导致lvl-ip进程退出

# ./suites/arp/suite-arp &
# pids="$pids $!"
# ./suites/icmp/suite-icmp &
# pids="$pids $!"

./suites/tcp/suite-curl &
pids="$pids $!"
./suites/tcp/suite-packet-delay &
pids="$pids $!"
./suites/tcp/suite-packet-duplication &
pids="$pids $!"
./suites/tcp/suite-packet-loss &
pids="$pids $!"

rc=0
for i in $pids; do
  wait $i
  pid_rc="$?"
  [ "$pid_rc" -ne 0 ] && rc="$pid_rc"
done

grep -iq "SUMMARY: ThreadSanitizer:|SUMMARY: AddressSanitizer:" $repo/logs/stdprint.log && echo -e "Possible a/tsan errors found."

echo
[ "$rc" -eq 0 ] && echo "Tests pass."
exit "$rc"
